# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2'

services:
  sabnzbd:
    user: sabnzbd
    image: wbvreeuwijk/sabnzbd:latest
    container_name: nzb_sabnzbd
    build: sabnzbd
    dns: 192.168.100.9
    networks:
      - proxy
    volumes:
      - /volume2/downloads/complete:/downloads/complete
      - download-incomplete:/downloads/incomplete
      - /volume2/docker/config/sabnzbd:/config

  sickrage:
    user: sabnzbd
    container_name: nzb_sickrage
    image: wbvreeuwijk/sickrage:latest
    depends_on:
      - sabnzbd
      - nzbmegasearch
    build: sickrage
    cpu_quota: 25000
    dns: 192.168.100.9
    ports:
      - 8082:8081
    networks:
      - proxy
    volumes:
      - /volume2/downloads/complete:/downloads/complete
      - /volume2/video:/video
      - /volume2/docker/config/sickrage:/config
  
#  sickbeard:
#    user: sabnzbd
#    container_name: nzb_sickbeard
#    image: wbvreeuwijk/sickbeard:latest
#    build: sickbeard
#    dns: 192.168.100.9
#    networks:
#      - proxy
#    volumes:
#      - /volume2/downloads/complete:/downloads/complete
#      - /volume2/video:/video
#      - /volume2/docker/config/sickbeard:/config

  couchpotato:
    user: sabnzbd
    container_name: nzb_couchpotato
    cpu_quota: 25000
    image: wbvreeuwijk/couchpotato:latest
    depends_on:
      - sabnzbd
      - nzbmegasearch
    build: couchpotato
    dns: 192.168.100.9
    networks:
      - proxy
    volumes:
      - /volume2/downloads/complete:/downloads/complete
      - /volume2/video:/video
      - /volume2/docker/config/couchpotato:/config

  subliminal:
    user: sabnzbd
    container_name: nzb_subliminal
    cpu_quota: 25000
    image: wbvreeuwijk/subliminal:latest
    build: subliminal
    dns: 192.168.100.9
    networks:
      - proxy
    volumes:
      - /volume2/video:/video

  nzbmegasearch:
    image: wbvreeuwijk/nzbmegasearch:latest
    container_name: nzb_nzbmegasearch
    build: nzbmegasearch
    dns: 192.168.100.9
    networks:
      - proxy
    volumes:
      - /volume2/docker/config/nzbmegasearch:/config
      
  spotweb:
    image: wbvreeuwijk/spotweb:latest
    container_name: nzb_spotweb
    cpu_quota: 25000
    build: spotweb
    dns: 192.168.100.9
    networks:
      - proxy
    environment:
      - MYSQL_PORT_3306_TCP_ADDR
      - MYSQL_ENV_MYSQL_DATABASE
      - MYSQL_ENV_MYSQL_USER
      - MYSQL_ENV_MYSQL_PASSWORD
    volumes:
      - spotweb-cache:/var/www/html/spotweb/cache

volumes:
  download-complete:
    driver: local
  download-incomplete:
    driver: local
  spotweb-cache:
    driver: local

networks:
  proxy:
    external:
      name: nginx_backend
