# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2'

services:
  sabnzbd:
    user: sabnzbd
    image: wbvreeuwijk/sabnzbd:latest
    container_name: nzb_sabnzbd
    build: sabnzbd
    ports: 
      - "8080:8080"
    volumes:
      - download-complete:/downloads/complete
      - download-incomplete:/downloads/incomplete
      - /volume2/docker/config/sabnzbd:/config

  sickbeard:
    user: sabnzbd
    container_name: nzb_sickbeard
    image: wbvreeuwijk/sickbeard:latest
    build: sickbeard
    ports:
      - "8081:8081"
    volumes:
      - download-complete:/downloads/complete
      - /volume2/video:/video
      - /volume2/docker/config/sickbeard:/config

  couchpotato:
    user: sabnzbd
    container_name: nzb_couchpotato
    image: wbvreeuwijk/couchpotato:latest
    build: couchpotato
    ports:
      - "5050:5050"
    volumes:
      - download-complete:/downloads/complete
      - /volume2/video:/video
      - /volume2/docker/config/couchpotato:/config

  subliminal:
    user: sabnzbd
    container_name: nzb_subliminal
    image: wbvreeuwijk/subliminal:latest
    build: subliminal
    volumes:
      - /volume2/video:/video

  nzbmegasearch:
    image: wbvreeuwijk/nzbmegasearch:latest
    container_name: nzb_nzbmegasearch
    build: nzbmegasearch
    ports:
      - "5005:5000"
    volumes:
      - /volume2/docker/config/nzbmegasearch:/config
      
  spotweb:
    image: wbvreeuwijk/spotweb:latest
    container_name: nzb_spotweb
    build: spotweb
    environment:
      MYSQL_PORT_3306_TCP_ADDR: 192.168.100.9
      MYSQL_ENV_MYSQL_DATABASE: spotweb
      MYSQL_ENV_MYSQL_USER:     spotweb
      MYSQL_ENV_MYSQL_PASSWORD: T1mbuk3!
    ports:
      - "18888:80"
    volumes:
      - spotweb-cache:/var/www/html/spotweb/cache
    

volumes:
  download-complete:
    driver: local
  download-incomplete:
    driver: local
  spotweb-cache:
    driver: local
