# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"

  couchpotato:
    container_name: nzb_couchpotato
    image: wbvreeuwijk/couchpotato:latest
    build: couchpotato
    ports:
      - "5050:5050"
    volumes:
      - couchpotato:/config

  spotweb:
    image: wbvreeuwijk/spotweb:latest
    container_name: nzb_spotweb
    build: spotweb
    environment:
      - MYSQL_PORT_3306_TCP_ADDR
      - MYSQL_ENV_MYSQL_DATABASE
      - MYSQL_ENV_MYSQL_USER
      - MYSQL_ENV_MYSQL_PASSWORD
    ports:
      - "80:80"
    volumes:
      - spotweb:/var/www/html/spotweb/cache
    
  home-assistant:
    image: homeassistant/home-assistant:latest
    container_name: home-assistant
    environment:
      - TZ
    ports:
      - "8123:8123"
    volumes:
      - home-assistant:/config 
    network_mode: "host"
     

volumes:
  couchpotato:
    driver: local
  spotweb:
    driver: local
  home-assistant:
    driver: local

